"""Structured planning, deterministic execution, and state verification."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator

from ..devices.base import DeviceRegistry
from ..devices.capabilities import CAPABILITIES, InvalidPlanArgument
from ..models import DeviceType
from .heuristics import should_use_planner  # noqa: F401  (P3 迁移后的再导出)

# should_use_planner 已迁至 heuristics.py（P3：判定逻辑单一模块）。
# 这里保留再导出，让既有导入路径 from src.agent.planning import should_use_planner
# 继续可用；新代码请直接 import src.agent.heuristics。


@dataclass(frozen=True)
class PlanningActionSpec:
    """一个 action 在规划侧的视图（喂 Planner 的文本 + 期望状态）。

    与 capabilities.ActionSpec 的分工：capabilities 是完整声明（含副作用实现），
    这里只取规划分支需要的两样东西。两处都从 CAPABILITIES 派生，不手写。
    """

    signature: str
    expected: Callable[[dict[str, Any], Any], dict[str, Any]]


@dataclass(frozen=True)
class PlanningToolSpec:
    """一个规划工具操作的设备类型及其全部合法 action。"""

    device_type: DeviceType
    actions: dict[str, PlanningActionSpec]


# 规划分支的单一数据源现在在 devices/capabilities.py（P0）。
#
# 为什么这份声明必须存在：Planner 走 `llm.with_structured_output(ExecutionPlan)`，
# 不像 ReAct 分支那样 `bind_tools`，所以工具 docstring 里写的 "on / off / ..."
# 一个字都到不了模型面前。模型只能凭常识猜 action，于是会写出 Home Assistant
# 风格的 turn_on / turn_off —— 这正是规划第一版反复失败的根因。把合法值显式喂给
# 它，第一版就该是对的。
#
# 为什么从 capabilities 派生而不是手写：这份信息以前散成三份手写副本（喂 Planner
# 的词表、expected_state_for_step 的近百行 if/elif、工具实现的 if/elif），漏改一处
# 的表现是 Planner 第一版计划稳定失败，且不报错。现在工具实现、合法 action、
# 期望状态三处同源于 capabilities，一致性由 tests/test_capabilities.py 钉住。
DEVICE_ACTION_SPECS: dict[str, PlanningToolSpec] = {
    cap.tool_name: PlanningToolSpec(
        cap.device_type,
        {
            action.name: PlanningActionSpec(action.signature, action.expected)
            for action in cap.actions
        },
    )
    for cap in CAPABILITIES
}

# 以下两个常量都是 DEVICE_ACTION_SPECS 的派生视图，不要手写。
PLANNING_TOOL_NAMES = tuple(DEVICE_ACTION_SPECS)
TOOL_ACTIONS: dict[str, str] = {
    tool_name: " / ".join(action.signature for action in spec.actions.values())
    for tool_name, spec in DEVICE_ACTION_SPECS.items()
}


class PlanStep(BaseModel):
    """One executable and independently verifiable device operation."""

    step_id: int = Field(ge=1)
    description: str = Field(min_length=1)
    # Literal 也从能力声明派生（P0）：Literal[tuple(...)] 会把元组展开成字面量。
    # structured output 靠它生成 JSON Schema 的 enum，从而在模型侧就约束住工具名；
    # 以前这里必须手写、靠一致性用例钉住，漏加时 Planner 明明该用新工具却被
    # pydantic 拒掉。现在新增设备自动带上，一致性由测试兜底。
    # 传感器故意不在其中：规划分支只做写操作，read_sensor 不该出现在计划里。
    tool_name: Literal[tuple(PLANNING_TOOL_NAMES)]  # type: ignore[valid-type]
    arguments: dict[str, Any]


class ExecutionPlan(BaseModel):
    """A bounded sequential plan generated by the planner model."""

    goal: str = Field(min_length=1)
    rationale: str = ""
    steps: list[PlanStep] = Field(min_length=2, max_length=8)

    @model_validator(mode="after")
    def normalize_step_ids(self):
        self.steps = [
            step.model_copy(update={"step_id": index})
            for index, step in enumerate(self.steps, start=1)
        ]
        return self


class VerificationResult(BaseModel):
    """Machine-checkable result produced after one plan step executes."""

    success: bool
    problem_type: Literal[
        "none", "device_not_found", "tool_error", "state_mismatch", "unsupported_action"
    ]
    reason: str
    actual_state: dict[str, Any] = Field(default_factory=dict)
    expected_state: dict[str, Any] = Field(default_factory=dict)


def planner_prompt(
    user_goal: str,
    registry: DeviceRegistry,
    memory_context: str,
    failure_feedback: str = "",
) -> str:
    """Build the strict prompt used for initial planning and replanning."""
    feedback = failure_feedback or "无，这是第一次规划。"
    actions = "\n".join(f"  · {tool}: {spec}" for tool, spec in TOOL_ACTIONS.items())
    return f"""你是智能家居任务规划器。请把用户目标拆成 2 到 8 个顺序执行的原子步骤。

用户目标：{user_goal}

可用设备：
{registry.get_device_list_prompt()}

相关长期记忆：
{memory_context}

上一次执行失败信息：
{feedback}

规则：
1. 每一步只能调用一个工具，工具必须是 {', '.join(PLANNING_TOOL_NAMES)} 之一。
2. arguments.action 只能取下列合法值，括号内是该 action 需要附带的参数；
   不要使用 turn_on / turn_off 这类其他平台的命名：
{actions}
3. arguments 必须严格符合对应工具参数；device_name 使用设备中文名称。
4. 不使用 activate_scene，因为本分支用于自定义多步骤目标。
5. 不添加用户没有要求的设备操作。
6. 如果是重新规划，应针对失败原因调整步骤或参数，但仍保持用户原目标。
7. 只输出结构化 ExecutionPlan，不输出额外文本。
"""


def plan_approval_payload(plan: dict[str, Any]) -> dict[str, Any]:
    """Create a serializable interrupt payload for a generated plan."""
    steps = plan.get("steps", [])
    lines = [f"{step['step_id']}. {step['description']}" for step in steps]
    summary = "\n".join(lines)
    return {
        "kind": "plan_approval",
        "question": f"已生成 {len(steps)} 步执行计划，是否开始执行？\n{summary}",
        "risk_level": "medium",
        "summary": summary,
        "plan": plan,
    }


def _unsupported_action(tool_name: str, action: Any) -> str:
    """Build an unsupported-action message that names the valid choices.

    重新规划时这条 feedback 会回喂给 Planner，所以带上合法值列表比只说
    "unsupported action" 有用得多 —— 否则模型只能凭常识反推正确写法，弱一点的
    模型可能改成 close/disable 又错一轮，白白耗掉重新规划额度。
    """
    spec = TOOL_ACTIONS.get(tool_name, "")
    suffix = f"（{tool_name} 仅支持 {spec}）" if spec else ""
    return f"unsupported action: {action}{suffix}"


def expected_state_for_step(
    step: dict[str, Any], registry: DeviceRegistry,
) -> tuple[str | None, dict[str, Any], str | None]:
    """Resolve the target and expected state before executing a plan step."""
    tool_name = step.get("tool_name", "")
    args = step.get("arguments", {})
    spec = DEVICE_ACTION_SPECS.get(tool_name)
    if spec is None:
        return None, {}, "unsupported tool"
    device = registry.find(str(args.get("device_name", "")), spec.device_type)
    if device is None:
        return None, {}, "device not found or ambiguous"

    action = args.get("action")
    action_spec = spec.actions.get(action) if isinstance(action, str) else None
    if action_spec is None:
        return device.device_id, {}, _unsupported_action(tool_name, action)
    try:
        return device.device_id, action_spec.expected(args, device), None
    except InvalidPlanArgument as exc:
        return device.device_id, {}, str(exc)


def verify_step(
    registry: DeviceRegistry,
    device_id: str | None,
    expected_state: dict[str, Any],
    tool_result: str,
    preparation_error: str | None = None,
) -> VerificationResult:
    """Verify execution using the actual registry state, not model self-report."""
    if device_id is None:
        return VerificationResult(
            success=False,
            problem_type="device_not_found",
            reason=preparation_error or "target device was not resolved",
            expected_state=expected_state,
        )
    if preparation_error:
        return VerificationResult(
            success=False,
            problem_type="unsupported_action",
            reason=preparation_error,
            expected_state=expected_state,
        )
    if tool_result.startswith("❌"):
        return VerificationResult(
            success=False,
            problem_type="tool_error",
            reason=tool_result,
            expected_state=expected_state,
        )

    device = registry.get(device_id)
    if device is None:
        return VerificationResult(
            success=False,
            problem_type="device_not_found",
            reason=f"device {device_id} disappeared after execution",
            expected_state=expected_state,
        )
    actual = {name: _plain_value(getattr(device, name, None)) for name in expected_state}
    expected = {name: _plain_value(value) for name, value in expected_state.items()}
    mismatches = {
        name: {"expected": expected[name], "actual": actual[name]}
        for name in expected
        if actual[name] != expected[name]
    }
    if mismatches:
        return VerificationResult(
            success=False,
            problem_type="state_mismatch",
            reason=f"device state mismatch: {mismatches}",
            actual_state=actual,
            expected_state=expected,
        )
    return VerificationResult(
        success=True,
        problem_type="none",
        reason="actual device state matches the expected state",
        actual_state=actual,
        expected_state=expected,
    )


def _plain_value(value: Any) -> Any:
    return getattr(value, "value", value)
