"""Structured planning, deterministic execution, and state verification."""

from __future__ import annotations

import re
from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator

from ..devices.base import DeviceRegistry
from ..models import DeviceType


PLANNING_TOOL_NAMES = (
    "control_light",
    "control_ac",
    "control_tv",
    "control_curtain",
)


class PlanStep(BaseModel):
    """One executable and independently verifiable device operation."""

    step_id: int = Field(ge=1)
    description: str = Field(min_length=1)
    tool_name: Literal[
        "control_light", "control_ac", "control_tv", "control_curtain"
    ]
    arguments: dict[str, Any]


class ExecutionPlan(BaseModel):
    """A bounded sequential plan generated by the planner model."""

    goal: str = Field(min_length=1)
    rationale: str = ""
    steps: list[PlanStep] = Field(min_length=2, max_length=8)

    @model_validator(mode="after")
    def normalize_step_ids(self):
        self.steps = [
            step.model_copy(update={"step_id": index})
            for index, step in enumerate(self.steps, start=1)
        ]
        return self


class VerificationResult(BaseModel):
    """Machine-checkable result produced after one plan step executes."""

    success: bool
    problem_type: Literal[
        "none", "device_not_found", "tool_error", "state_mismatch", "unsupported_action"
    ]
    reason: str
    actual_state: dict[str, Any] = Field(default_factory=dict)
    expected_state: dict[str, Any] = Field(default_factory=dict)


def should_use_planner(text: str) -> bool:
    """Conservatively route explicit custom multi-action requests to Planner."""
    normalized = text.strip()
    if not normalized:
        return False

    # Predefined scene requests remain on the existing ReAct + scene approval path.
    if any(marker in normalized for marker in (
        "回家模式", "离家模式", "睡眠模式", "观影模式", "起床模式",
        "我回来了", "我要出门", "我要睡", "看电影", "起床了",
    )):
        return False

    action_patterns = (
        r"打开", r"开启", r"关闭", r"关掉", r"调到", r"设为",
        r"调成", r"拉开", r"拉上", r"静音", r"切换",
    )
    action_count = sum(len(re.findall(pattern, normalized)) for pattern in action_patterns)
    device_kinds = sum(
        1 for keyword in ("灯", "空调", "电视", "窗帘") if keyword in normalized
    )
    connectors = any(
        connector in normalized
        for connector in ("并且", "然后", "同时", "再把", "再将", "以及", "顺便")
    )
    return action_count >= 2 and (device_kinds >= 2 or connectors)


def planner_prompt(
    user_goal: str,
    registry: DeviceRegistry,
    memory_context: str,
    failure_feedback: str = "",
) -> str:
    """Build the strict prompt used for initial planning and replanning."""
    feedback = failure_feedback or "无，这是第一次规划。"
    return f"""你是智能家居任务规划器。请把用户目标拆成 2 到 8 个顺序执行的原子步骤。

用户目标：{user_goal}

可用设备：
{registry.get_device_list_prompt()}

相关长期记忆：
{memory_context}

上一次执行失败信息：
{feedback}

规则：
1. 每一步只能调用一个工具，工具必须是 {', '.join(PLANNING_TOOL_NAMES)} 之一。
2. arguments 必须严格符合对应工具参数；device_name 使用设备中文名称。
3. 不使用 activate_scene，因为本分支用于自定义多步骤目标。
4. 不添加用户没有要求的设备操作。
5. 如果是重新规划，应针对失败原因调整步骤或参数，但仍保持用户原目标。
6. 只输出结构化 ExecutionPlan，不输出额外文本。
"""


def plan_approval_payload(plan: dict[str, Any]) -> dict[str, Any]:
    """Create a serializable interrupt payload for a generated plan."""
    steps = plan.get("steps", [])
    lines = [f"{step['step_id']}. {step['description']}" for step in steps]
    summary = "\n".join(lines)
    return {
        "kind": "plan_approval",
        "question": f"已生成 {len(steps)} 步执行计划，是否开始执行？\n{summary}",
        "risk_level": "medium",
        "summary": summary,
        "plan": plan,
    }


def expected_state_for_step(
    step: dict[str, Any], registry: DeviceRegistry,
) -> tuple[str | None, dict[str, Any], str | None]:
    """Resolve the target and expected state before executing a plan step."""
    tool_name = step.get("tool_name")
    args = step.get("arguments", {})
    mapping = {
        "control_light": DeviceType.LIGHT,
        "control_ac": DeviceType.AC,
        "control_tv": DeviceType.TV,
        "control_curtain": DeviceType.CURTAIN,
    }
    device_type = mapping.get(tool_name)
    if device_type is None:
        return None, {}, "unsupported tool"
    device = registry.find(str(args.get("device_name", "")), device_type)
    if device is None:
        return None, {}, "device not found or ambiguous"

    action = args.get("action")
    expected: dict[str, Any]
    if tool_name == "control_light":
        if action == "on":
            expected = {"power": True}
        elif action == "off":
            expected = {"power": False}
        elif action == "set_brightness":
            expected = {"power": True, "brightness": max(0, min(100, int(args.get("brightness", 50))))}
        elif action == "set_color":
            expected = {"power": True, "color": args.get("color", "暖白")}
        else:
            return device.device_id, {}, f"unsupported action: {action}"
    elif tool_name == "control_ac":
        if action == "on":
            expected = {
                "power": True,
                "temperature": max(16, min(30, int(args.get("temperature", 26)))),
                "mode": args.get("mode", "cool"),
            }
        elif action == "off":
            expected = {"power": False}
        elif action == "set_temp":
            expected = {"power": True, "temperature": max(16, min(30, int(args.get("temperature", 26))))}
        elif action == "set_mode":
            expected = {"power": True, "mode": args.get("mode", "cool")}
        elif action == "set_fan":
            expected = {"fan_speed": args.get("fan_speed", "auto")}
        else:
            return device.device_id, {}, f"unsupported action: {action}"
    elif tool_name == "control_tv":
        if action == "on":
            expected = {"power": True}
        elif action == "off":
            expected = {"power": False}
        elif action == "set_volume":
            expected = {"volume": max(0, min(100, int(args.get("volume", 30))))}
        elif action == "mute":
            expected = {"muted": not device.muted}
        elif action == "set_channel":
            expected = {"power": True, "channel": args.get("channel", "HDMI 1")}
        else:
            return device.device_id, {}, f"unsupported action: {action}"
    else:
        if action == "open":
            expected = {"position": 100}
        elif action == "close":
            expected = {"position": 0}
        elif action == "set_position":
            expected = {"position": max(0, min(100, int(args.get("percentage", 100))))}
        else:
            return device.device_id, {}, f"unsupported action: {action}"
    return device.device_id, expected, None


def verify_step(
    registry: DeviceRegistry,
    device_id: str | None,
    expected_state: dict[str, Any],
    tool_result: str,
    preparation_error: str | None = None,
) -> VerificationResult:
    """Verify execution using the actual registry state, not model self-report."""
    if device_id is None:
        return VerificationResult(
            success=False,
            problem_type="device_not_found",
            reason=preparation_error or "target device was not resolved",
            expected_state=expected_state,
        )
    if preparation_error:
        return VerificationResult(
            success=False,
            problem_type="unsupported_action",
            reason=preparation_error,
            expected_state=expected_state,
        )
    if tool_result.startswith("❌"):
        return VerificationResult(
            success=False,
            problem_type="tool_error",
            reason=tool_result,
            expected_state=expected_state,
        )

    device = registry.get(device_id)
    if device is None:
        return VerificationResult(
            success=False,
            problem_type="device_not_found",
            reason=f"device {device_id} disappeared after execution",
            expected_state=expected_state,
        )
    actual = {name: _plain_value(getattr(device, name, None)) for name in expected_state}
    expected = {name: _plain_value(value) for name, value in expected_state.items()}
    mismatches = {
        name: {"expected": expected[name], "actual": actual[name]}
        for name in expected
        if actual[name] != expected[name]
    }
    if mismatches:
        return VerificationResult(
            success=False,
            problem_type="state_mismatch",
            reason=f"device state mismatch: {mismatches}",
            actual_state=actual,
            expected_state=expected,
        )
    return VerificationResult(
        success=True,
        problem_type="none",
        reason="actual device state matches the expected state",
        actual_state=actual,
        expected_state=expected,
    )


def _plain_value(value: Any) -> Any:
    return getattr(value, "value", value)
