"""Structured planning, deterministic execution, and state verification."""

from __future__ import annotations

import re
from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator

from ..devices.base import DeviceRegistry
from ..models import DeviceType


PLANNING_TOOL_NAMES = (
    "control_light",
    "control_ac",
    "control_tv",
    "control_curtain",
    "control_humidifier",
)

# 每个工具的合法 action 及其附带参数。
#
# 为什么要单独维护这份词表：Planner 走 `llm.with_structured_output(ExecutionPlan)`，
# 不像 ReAct 分支那样 `bind_tools`，所以工具 docstring 里写的 "on / off / ..."
# 一个字都到不了模型面前。模型只能凭常识猜 action，于是会写出 Home Assistant
# 风格的 turn_on / turn_off —— 这正是规划第一版反复失败的根因。把合法值显式喂给
# 它，第一版就该是对的。
#
# 三处 action 枚举必须保持同步：工具实现的 if/elif、expected_state_for_step 的
# if/elif、以及这里。它们都靠手写（if/elif 无法反射），tests 用一致性用例钉住。
TOOL_ACTIONS: dict[str, str] = {
    "control_light": "on / off / set_brightness(brightness) / set_color(color)",
    "control_ac": (
        "on(可带 temperature、mode) / off / set_temp(temperature) / "
        "set_mode(mode) / set_fan(fan_speed)"
    ),
    "control_tv": "on / off / set_volume(volume) / mute / set_channel(channel)",
    "control_curtain": "open / close / set_position(percentage)",
    "control_humidifier": (
        "on / off / set_humidity(target_humidity) / set_mist_level(mist_level)"
    ),
}


class PlanStep(BaseModel):
    """One executable and independently verifiable device operation."""

    step_id: int = Field(ge=1)
    description: str = Field(min_length=1)
    tool_name: Literal[
        "control_light", "control_ac", "control_tv", "control_curtain",
        "control_humidifier",
    ]
    arguments: dict[str, Any]


class ExecutionPlan(BaseModel):
    """A bounded sequential plan generated by the planner model."""

    goal: str = Field(min_length=1)
    rationale: str = ""
    steps: list[PlanStep] = Field(min_length=2, max_length=8)

    @model_validator(mode="after")
    def normalize_step_ids(self):
        self.steps = [
            step.model_copy(update={"step_id": index})
            for index, step in enumerate(self.steps, start=1)
        ]
        return self


class VerificationResult(BaseModel):
    """Machine-checkable result produced after one plan step executes."""

    success: bool
    problem_type: Literal[
        "none", "device_not_found", "tool_error", "state_mismatch", "unsupported_action"
    ]
    reason: str
    actual_state: dict[str, Any] = Field(default_factory=dict)
    expected_state: dict[str, Any] = Field(default_factory=dict)


def should_use_planner(text: str) -> bool:
    """Conservatively route explicit custom multi-action requests to Planner."""
    normalized = text.strip()
    if not normalized:
        return False

    # Predefined scene requests remain on the existing ReAct + scene approval path.
    if any(marker in normalized for marker in (
        "回家模式", "离家模式", "睡眠模式", "观影模式", "起床模式",
        "我回来了", "我要出门", "我要睡", "看电影", "起床了",
    )):
        return False

    action_patterns = (
        r"打开", r"开启", r"关闭", r"关掉", r"调到", r"设为",
        r"调成", r"拉开", r"拉上", r"静音", r"切换",
    )
    action_count = sum(len(re.findall(pattern, normalized)) for pattern in action_patterns)
    device_kinds = sum(
        1 for keyword in ("灯", "空调", "电视", "窗帘", "加湿器") if keyword in normalized
    )
    connectors = any(
        connector in normalized
        for connector in ("并且", "然后", "同时", "再把", "再将", "以及", "顺便")
    )
    return action_count >= 2 and (device_kinds >= 2 or connectors)


def planner_prompt(
    user_goal: str,
    registry: DeviceRegistry,
    memory_context: str,
    failure_feedback: str = "",
) -> str:
    """Build the strict prompt used for initial planning and replanning."""
    feedback = failure_feedback or "无，这是第一次规划。"
    actions = "\n".join(f"  · {tool}: {spec}" for tool, spec in TOOL_ACTIONS.items())
    return f"""你是智能家居任务规划器。请把用户目标拆成 2 到 8 个顺序执行的原子步骤。

用户目标：{user_goal}

可用设备：
{registry.get_device_list_prompt()}

相关长期记忆：
{memory_context}

上一次执行失败信息：
{feedback}

规则：
1. 每一步只能调用一个工具，工具必须是 {', '.join(PLANNING_TOOL_NAMES)} 之一。
2. arguments.action 只能取下列合法值，括号内是该 action 需要附带的参数；
   不要使用 turn_on / turn_off 这类其他平台的命名：
{actions}
3. arguments 必须严格符合对应工具参数；device_name 使用设备中文名称。
4. 不使用 activate_scene，因为本分支用于自定义多步骤目标。
5. 不添加用户没有要求的设备操作。
6. 如果是重新规划，应针对失败原因调整步骤或参数，但仍保持用户原目标。
7. 只输出结构化 ExecutionPlan，不输出额外文本。
"""


def plan_approval_payload(plan: dict[str, Any]) -> dict[str, Any]:
    """Create a serializable interrupt payload for a generated plan."""
    steps = plan.get("steps", [])
    lines = [f"{step['step_id']}. {step['description']}" for step in steps]
    summary = "\n".join(lines)
    return {
        "kind": "plan_approval",
        "question": f"已生成 {len(steps)} 步执行计划，是否开始执行？\n{summary}",
        "risk_level": "medium",
        "summary": summary,
        "plan": plan,
    }


def _unsupported_action(tool_name: str, action: Any) -> str:
    """Build an unsupported-action message that names the valid choices.

    重新规划时这条 feedback 会回喂给 Planner，所以带上合法值列表比只说
    "unsupported action" 有用得多 —— 否则模型只能凭常识反推正确写法，弱一点的
    模型可能改成 close/disable 又错一轮，白白耗掉重新规划额度。
    """
    spec = TOOL_ACTIONS.get(tool_name, "")
    suffix = f"（{tool_name} 仅支持 {spec}）" if spec else ""
    return f"unsupported action: {action}{suffix}"


def expected_state_for_step(
    step: dict[str, Any], registry: DeviceRegistry,
) -> tuple[str | None, dict[str, Any], str | None]:
    """Resolve the target and expected state before executing a plan step."""
    tool_name = step.get("tool_name")
    args = step.get("arguments", {})
    mapping = {
        "control_light": DeviceType.LIGHT,
        "control_ac": DeviceType.AC,
        "control_tv": DeviceType.TV,
        "control_curtain": DeviceType.CURTAIN,
        "control_humidifier": DeviceType.HUMIDIFIER,
    }
    device_type = mapping.get(tool_name)
    if device_type is None:
        return None, {}, "unsupported tool"
    device = registry.find(str(args.get("device_name", "")), device_type)
    if device is None:
        return None, {}, "device not found or ambiguous"

    action = args.get("action")
    expected: dict[str, Any]
    if tool_name == "control_light":
        if action == "on":
            expected = {"power": True}
        elif action == "off":
            expected = {"power": False}
        elif action == "set_brightness":
            expected = {"power": True, "brightness": max(0, min(100, int(args.get("brightness", 50))))}
        elif action == "set_color":
            expected = {"power": True, "color": args.get("color", "暖白")}
        else:
            return device.device_id, {}, _unsupported_action(tool_name, action)
    elif tool_name == "control_ac":
        if action == "on":
            expected = {
                "power": True,
                "temperature": max(16, min(30, int(args.get("temperature", 26)))),
                "mode": args.get("mode", "cool"),
            }
        elif action == "off":
            expected = {"power": False}
        elif action == "set_temp":
            expected = {"power": True, "temperature": max(16, min(30, int(args.get("temperature", 26))))}
        elif action == "set_mode":
            expected = {"power": True, "mode": args.get("mode", "cool")}
        elif action == "set_fan":
            expected = {"fan_speed": args.get("fan_speed", "auto")}
        else:
            return device.device_id, {}, _unsupported_action(tool_name, action)
    elif tool_name == "control_tv":
        if action == "on":
            expected = {"power": True}
        elif action == "off":
            expected = {"power": False}
        elif action == "set_volume":
            expected = {"volume": max(0, min(100, int(args.get("volume", 30))))}
        elif action == "mute":
            expected = {"muted": not device.muted}
        elif action == "set_channel":
            expected = {"power": True, "channel": args.get("channel", "HDMI 1")}
        else:
            return device.device_id, {}, _unsupported_action(tool_name, action)
    elif tool_name == "control_curtain":
        if action == "open":
            expected = {"position": 100}
        elif action == "close":
            expected = {"position": 0}
        elif action == "set_position":
            expected = {"position": max(0, min(100, int(args.get("percentage", 100))))}
        else:
            return device.device_id, {}, _unsupported_action(tool_name, action)
    elif tool_name == "control_humidifier":
        if action == "on":
            expected = {"power": True}
        elif action == "off":
            expected = {"power": False}
        elif action == "set_humidity":
            expected = {
                "power": True,
                "target_humidity": max(30, min(80, int(args.get("target_humidity", 60)))),
            }
        elif action == "set_mist_level":
            expected = {"power": True, "mist_level": args.get("mist_level", "auto")}
        else:
            return device.device_id, {}, _unsupported_action(tool_name, action)
    else:
        return device.device_id, {}, f"unsupported tool: {tool_name}"
    return device.device_id, expected, None


def verify_step(
    registry: DeviceRegistry,
    device_id: str | None,
    expected_state: dict[str, Any],
    tool_result: str,
    preparation_error: str | None = None,
) -> VerificationResult:
    """Verify execution using the actual registry state, not model self-report."""
    if device_id is None:
        return VerificationResult(
            success=False,
            problem_type="device_not_found",
            reason=preparation_error or "target device was not resolved",
            expected_state=expected_state,
        )
    if preparation_error:
        return VerificationResult(
            success=False,
            problem_type="unsupported_action",
            reason=preparation_error,
            expected_state=expected_state,
        )
    if tool_result.startswith("❌"):
        return VerificationResult(
            success=False,
            problem_type="tool_error",
            reason=tool_result,
            expected_state=expected_state,
        )

    device = registry.get(device_id)
    if device is None:
        return VerificationResult(
            success=False,
            problem_type="device_not_found",
            reason=f"device {device_id} disappeared after execution",
            expected_state=expected_state,
        )
    actual = {name: _plain_value(getattr(device, name, None)) for name in expected_state}
    expected = {name: _plain_value(value) for name, value in expected_state.items()}
    mismatches = {
        name: {"expected": expected[name], "actual": actual[name]}
        for name in expected
        if actual[name] != expected[name]
    }
    if mismatches:
        return VerificationResult(
            success=False,
            problem_type="state_mismatch",
            reason=f"device state mismatch: {mismatches}",
            actual_state=actual,
            expected_state=expected,
        )
    return VerificationResult(
        success=True,
        problem_type="none",
        reason="actual device state matches the expected state",
        actual_state=actual,
        expected_state=expected,
    )


def _plain_value(value: Any) -> Any:
    return getattr(value, "value", value)
